# Generated by Django 4.0.6 on 2022-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
