# Generated by Django 4.0.6 on 2022-08-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0003_chairman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
