# Generated by Django 4.0.6 on 2022-08-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0005_chairman_bigimage_alter_chairman_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=20)),
                ('desc1', models.TextField()),
                ('title2', models.CharField(max_length=20)),
                ('desc2', models.TextField()),
                ('title3', models.CharField(max_length=20)),
                ('desc3', models.TextField()),
                ('title4', models.CharField(max_length=20)),
                ('desc4', models.TextField()),
            ],
        ),
    ]
