# Generated by Django 4.0.6 on 2022-08-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0006_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=40)),
                ('pic', models.ImageField(upload_to='static/propertiesimg')),
            ],
        ),
    ]
