# Generated by Django 4.0.6 on 2022-08-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0007_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=30)),
                ('subtitle1', models.CharField(max_length=30)),
                ('desc1', models.TextField()),
                ('title2', models.CharField(max_length=30)),
                ('subtitle2', models.CharField(max_length=30)),
                ('desc2', models.TextField()),
                ('title3', models.CharField(max_length=30)),
                ('desc3', models.TextField()),
                ('subtitle3', models.CharField(max_length=30)),
            ],
        ),
    ]
