# Generated by Django 4.0.6 on 2022-08-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0009_alter_slider_subtitle1_alter_slider_subtitle2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='desc1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='desc2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='desc3',
            field=models.TextField(null=True),
        ),
    ]
