# Generated by Django 4.0.6 on 2022-08-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0010_alter_slider_desc1_alter_slider_desc2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image1',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image2',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image3',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
