# Generated by Django 4.0.6 on 2022-08-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0011_slider_image1_slider_image2_slider_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/sliderimg'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image2',
            field=models.ImageField(null=True, upload_to='static/sliderimg'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image3',
            field=models.ImageField(null=True, upload_to='static/sliderimg'),
        ),
    ]
