# Generated by Django 4.0.6 on 2022-08-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0012_alter_slider_image1_alter_slider_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairman',
            name='bigimage',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='location',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='title',
        ),
        migrations.AddField(
            model_name='properties',
            name='location1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='location2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='location3',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='pic1',
            field=models.ImageField(null=True, upload_to='static/propertiesimg'),
        ),
        migrations.AddField(
            model_name='properties',
            name='pic2',
            field=models.ImageField(null=True, upload_to='static/propertiesimg'),
        ),
        migrations.AddField(
            model_name='properties',
            name='pic3',
            field=models.ImageField(null=True, upload_to='static/propertiesimg'),
        ),
        migrations.AddField(
            model_name='properties',
            name='title1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='title2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='title3',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
