# Generated by Django 4.0.6 on 2022-08-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0014_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('role', models.TextField(max_length=50)),
                ('img', models.ImageField(upload_to='static/boardimg')),
            ],
        ),
    ]
