# Generated by Django 4.0.6 on 2022-08-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0015_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
