# Generated by Django 4.0.6 on 2022-08-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0016_alter_board_name_alter_board_role_alter_board_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='detailed_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
