# Generated by Django 4.0.6 on 2022-08-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0017_chairman_detailed_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairman',
            name='detailed_description',
        ),
        migrations.AddField(
            model_name='chairman',
            name='paragraph1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chairman',
            name='paragraph2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chairman',
            name='paragraph3',
            field=models.TextField(null=True),
        ),
    ]
