# Generated by Django 4.0.6 on 2022-08-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0018_remove_chairman_detailed_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('location', models.CharField(max_length=40, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/projectsimg')),
            ],
        ),
    ]
