# Generated by Django 4.0.6 on 2022-08-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0020_companynews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='companynewsfile'),
        ),
    ]
