# Generated by Django 4.0.6 on 2022-08-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0022_alter_companynews_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynews',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
