# Generated by Django 4.0.6 on 2022-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0025_alter_companynews_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
