# Generated by Django 4.0.6 on 2022-08-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0033_alter_projects_image_projectsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsimage',
            name='projectimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanchaykos.projects'),
        ),
    ]
