# Generated by Django 4.0.6 on 2022-08-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0034_alter_projectsimage_projectimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsimage',
            old_name='image',
            new_name='images',
        ),
    ]
