# Generated by Django 4.0.6 on 2022-08-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0035_rename_image_projectsimage_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Properties',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='subtitle1',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='subtitle2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='desc2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='desc3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='subtitle3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title3',
        ),
        migrations.AddField(
            model_name='slider',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
