# Generated by Django 4.0.6 on 2022-08-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0036_delete_properties_rename_desc1_slider_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='footer_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
