# Generated by Django 4.0.6 on 2022-08-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanchaykos', '0038_companycontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontacts',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
